# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera.proto',
  package='camera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x18\n\x05image\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x12\n\x10SubscribeRequest2E\n\x0cimageService\x12\x35\n\x08getImage\x12\x18.camera.SubscribeRequest\x1a\r.camera.image\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='camera.image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='camera.image.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=48,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='camera.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['image'] = _IMAGE
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.image)
  })
_sym_db.RegisterMessage(image)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)



_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='imageService',
  full_name='camera.imageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=70,
  serialized_end=139,
  methods=[
  _descriptor.MethodDescriptor(
    name='getImage',
    full_name='camera.imageService.getImage',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['imageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
