# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera.proto',
  package='camera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"9\n\x05image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\timageData\x18\x03 \x01(\x0c\"\x12\n\x10subscribeRequest2D\n\x0bimageStream\x12\x35\n\x08getImage\x12\x18.camera.subscribeRequest\x1a\r.camera.image\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='camera.image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='camera.image.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='camera.image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageData', full_name='camera.image.imageData', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=81,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='subscribeRequest',
  full_name='camera.subscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['image'] = _IMAGE
DESCRIPTOR.message_types_by_name['subscribeRequest'] = _SUBSCRIBEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.image)
  })
_sym_db.RegisterMessage(image)

subscribeRequest = _reflection.GeneratedProtocolMessageType('subscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.subscribeRequest)
  })
_sym_db.RegisterMessage(subscribeRequest)



_IMAGESTREAM = _descriptor.ServiceDescriptor(
  name='imageStream',
  full_name='camera.imageStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=103,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='getImage',
    full_name='camera.imageStream.getImage',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_IMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESTREAM)

DESCRIPTOR.services_by_name['imageStream'] = _IMAGESTREAM

# @@protoc_insertion_point(module_scope)
